# permissions for end users to view customkinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customkind-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k8soperator
    app.kubernetes.io/part-of: k8soperator
    app.kubernetes.io/managed-by: kustomize
  name: customkind-viewer-role
rules:
- apiGroups:
  - yevhen-test-group.yevhenzavhorodniipersonal
  resources:
  - customkinds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - yevhen-test-group.yevhenzavhorodniipersonal
  resources:
  - customkinds/status
  verbs:
  - get
