---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - yevhen-test-group.yevhenzavhorodniipersonal
  resources:
  - customkinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - yevhen-test-group.yevhenzavhorodniipersonal
  resources:
  - customkinds/finalizers
  verbs:
  - update
- apiGroups:
  - yevhen-test-group.yevhenzavhorodniipersonal
  resources:
  - customkinds/status
  verbs:
  - get
  - patch
  - update
